name: Deploy with GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout main repository
      - name: Checkout main repository
        uses: actions/checkout@v3
      
      # Checkout syntaxes from external repository
      - name: Checkout syntaxes from external repository
        uses: actions/checkout@v3
        with:
          repository: 'barrettotte/vscode-ibmi-languages'
          path: 'syntaxes'
          ref: 'master'
      
      # Copy syntaxes to the appropriate directory
      - name: Create syntaxes directory and copy syntaxes
        run: |
          mkdir -p includes/syntaxes
          cp -r syntaxes/syntaxes/* includes/syntaxes/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # The branch you want to push to
          publish_dir: ./  # The directory you want to push to GitHub Pages