name: Deploy with GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout main repository
      - name: Checkout main repository
        uses: actions/checkout@v3
      
      # Checkout syntaxes from external repository
      - name: Checkout syntaxes from external repository
        uses: actions/checkout@v3
        with:
          repository: 'barrettotte/vscode-ibmi-languages'
          path: 'external-syntaxes'
          ref: 'master'

      # Submodule fix
      - name: Remove any existing .git directory within syntaxes (prevent it from becoming a submodule)
        run: rm -rf external-syntaxes/.git
      
      # Copy syntaxes to the appropriate directory
      - name: Create syntaxes directory and copy syntaxes
        run: |
          mkdir -p include/syntaxes
          cp -r external-syntaxes/* include/syntaxes/

      # List contents of syntaxes copy
      - name: List contents of include/syntaxes
        run: ls -R include/syntaxes  

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages 
          publish_dir: ./ 
