name: Checkout syntaxes directory

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          path: 'main-repo'

      - name: Sparse checkout syntaxes from vscode-ibmi-languages
        uses: actions/checkout@v3
        with:
          repository: 'barrettotte/vscode-ibmi-languages'
          path: 'temp-repo'
          ref: 'master'  # Use the correct branch name here

      - name: Initialize sparse-checkout for syntaxes directory
        run: |
          cd temp-repo
          git sparse-checkout init --cone
          git sparse-checkout set syntaxes

      - name: Perform the checkout
        run: |
          cd temp-repo
          git checkout

      - name: Move syntaxes to the desired directory
        run: |
          mkdir -p main-repo/includes
          mv temp-repo/syntaxes main-re
